(() => {
  const BOT="OO_PBot", OWNER_ID="1523406780"; const tg=window.Telegram?.WebApp;
  const state={view:"home",listMode:"",tracks:[],current:null,currentIndex:-1,profile:null,artist:"",artistFollowed:false,isAdmin:false,suggestTimer:null,playlists:[],activePlaylist:null,searchMode:"song",shuffle:false,repeat:"off",trendPeriod:"week"};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], audio=$("#audio");
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  function haptic(k="light"){try{tg?.HapticFeedback?.impactOccurred(k)}catch(_){}}
  function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2200)}
  function loading(on,text="Finding your music…"){$("#loadingText").textContent=text;$("#loading").classList.toggle("hidden",!on)}
  async function api(path,options={}){const headers={"X-Telegram-Init-Data":tg?.initData||"",...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})};const r=await fetch(path,{...options,headers});if(!r.ok){const m=(await r.text()).trim()||`Request failed (${r.status})`;if(r.status===401)fatal(m);throw new Error(m)}return r.json()}
  function fatal(text){$("#fatalText").textContent=text;$("#fatal").classList.remove("hidden")}
  function viewEl(name){if(name==="home")return $("#homeView");if(name==="profile")return $("#profileView");if(name==="artist")return $("#artistView");if(name==="admin")return $("#adminView");if(name==="playlists")return $("#playlistsView");if(name==="following")return $("#followingView");return $("#listView")}
  function showView(name){state.view=name;$$('.view').forEach(v=>v.classList.remove('active'));viewEl(name).classList.add('active');$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===name||(["top","artist","admin","following"].includes(name)&&t.dataset.tab==="home")));try{name!=="home"?tg?.BackButton?.show():tg?.BackButton?.hide()}catch(_){}hideSuggestions();window.scrollTo({top:0,behavior:"smooth"})}
  const art=i=>["♪","♫","♬","♡"][i%4];
  function makeTrackRow(t,i){const row=document.createElement('article');row.className='track';row.innerHTML=`<button class="track-art icon-btn play-row">${art(i)}</button><div class="track-meta"><strong>${esc(t.title||t.name)}</strong><button class="artist-link" type="button">${esc(t.performer||"Unknown artist")}</button></div><div class="track-actions"><button class="icon-btn related">≈</button><button class="icon-btn fav ${t.favorite?"loved":""}">${t.favorite?"♥":"♡"}</button><button class="icon-btn download">⇩</button></div>`;row.querySelector('.play-row').onclick=()=>playTrack(t);row.querySelector('.track-meta strong').onclick=()=>playTrack(t);row.querySelector('.artist-link').onclick=e=>{e.stopPropagation();loadArtist(t.performer)};row.querySelector('.related').onclick=e=>{e.stopPropagation();loadRelated(t)};row.querySelector('.fav').onclick=async e=>{e.stopPropagation();await toggleFavorite(t,e.currentTarget)};row.querySelector('.download').onclick=e=>{e.stopPropagation();downloadTrack(t)};return row}
  function renderTracks(tracks,title,kicker,subtitle){state.tracks=tracks;$("#listTitle").textContent=title;$("#listKicker").textContent=kicker;$("#listSub").textContent=subtitle||"";const box=$("#trackList");box.innerHTML="";$("#emptyState").classList.toggle('hidden',tracks.length>0);tracks.forEach((t,i)=>box.appendChild(makeTrackRow(t,i)));$("#trendFilters").classList.toggle('hidden',state.listMode!=="top")}
  function renderArtistTracks(tracks){state.tracks=tracks;const b=$("#artistTrackList");b.innerHTML="";$("#artistEmpty").classList.toggle('hidden',tracks.length>0);tracks.forEach((t,i)=>b.appendChild(makeTrackRow(t,i)))}
  function hideSuggestions(){const b=$("#suggestions");b.classList.add('hidden');b.innerHTML=""}
  async function loadSuggestions(q,force=false){q=q.trim();if(state.searchMode!=="song"||q.length<2){hideSuggestions();return}try{const d=await api(`/api/suggest?q=${encodeURIComponent(q)}`),b=$("#suggestions");if(!d.suggestions?.length){if(force){b.innerHTML='<button class="suggest-empty">No learned match yet — press Search 🎀</button>';b.classList.remove('hidden')}else hideSuggestions();return}b.innerHTML=d.suggestions.map(x=>`<button class="suggest-item" type="button"><span>⌕</span><strong>${esc(x)}</strong></button>`).join('');[...b.querySelectorAll('.suggest-item')].forEach((btn,i)=>btn.onclick=()=>{$("#searchInput").value=d.suggestions[i];hideSuggestions();doSearch(d.suggestions[i])});b.classList.remove('hidden')}catch(_){if(force)toast('Suggestions are warming up 🎀')}}
  async function doSearch(query){hideSuggestions();if(state.searchMode==="artist"){return loadArtist(query)};loading(true,state.searchMode==="lyrics"?`Finding a song from those lyrics…`:`Searching for “${query}”…`);haptic();try{const path=state.searchMode==="lyrics"?'/api/lyrics':'/api/search';const d=await api(path,{method:'POST',body:JSON.stringify({query})});state.listMode=state.searchMode==="lyrics"?'lyrics':'search';showView('list');renderTracks(d.tracks,state.searchMode==="lyrics"?'Lyrics match':`“${d.query}”`,state.searchMode==="lyrics"?'🎤 IDENTIFIED FROM LYRICS':'SEARCH RESULTS',`${d.tracks.length} matches from Music Bunny`)}catch(e){toast(state.searchMode==="lyrics"?'I couldn’t identify that lyric yet 🎤':'Try one of the suggestions 🎀');showView('home');if(state.searchMode==="song"){$("#searchInput").value=query;await loadSuggestions(query,true)}}finally{loading(false)}}
  async function loadFavorites(){loading(true,'Opening your favorites…');try{const d=await api('/api/favorites');state.listMode='favorites';showView('list');renderTracks(d.tracks,'My Favorites','SAVED WITH 🩷',`${d.tracks.length} saved song${d.tracks.length===1?'':'s'}`)}catch(e){toast(e.message)}finally{loading(false)}}
  async function loadTop(period=state.trendPeriod){state.trendPeriod=period;loading(true,'Checking what everyone loves…');try{const d=await api(`/api/top?period=${period}`);state.listMode='top';showView('list');renderTracks(d.tracks,'Most Requested','TRENDING IN THE BOT',d.tracks.length?`Trending · ${period}`:'No trending songs yet');$$('#trendFilters button').forEach(b=>b.classList.toggle('active',b.dataset.period===period))}catch(e){toast(e.message)}finally{loading(false)}}
  async function loadRecommendations(){loading(true,'Making your mix…');try{const d=await api('/api/recommendations');state.listMode='recommendations';showView('list');renderTracks(d.tracks,'For You','✨ YOUR MUSIC MIX',d.tracks.length?'Based on your favorites, plays and artists':'Follow artists or play a few songs first')}catch(e){toast(e.message)}finally{loading(false)}}
  async function loadRecent(){loading(true,'Opening your recent songs…');try{const d=await api('/api/recent');state.listMode='recent';showView('list');renderTracks(d.tracks,'Recently Played','BACK IN A TAP',d.tracks.length?`${d.tracks.length} recent songs`:'Nothing played yet')}catch(e){toast(e.message)}finally{loading(false)}}
  async function loadProfile(){loading(true,'Building your music story…');try{const d=await api('/api/profile');state.profile=d.profile;renderProfile(d.profile);showView('profile')}catch(e){toast(e.message)}finally{loading(false)}}
  function renderProfile(p){$("#profileName").textContent=p.name;$("#profileUsername").textContent=p.username?`@${p.username}`:'MUSIC LOVER';$("#profileRank").textContent=p.rank;$("#statSearch").textContent=p.search_count;$("#statFav").textContent=p.favorite_count;$("#statTogether").textContent=p.songs_together;$("#profileBadge").textContent=p.badge;$("#topArtist").textContent=p.top_artist;$("#joinedDate").textContent=p.joined_date;const r=$("#recentSearches");r.innerHTML=p.recent_searches.length?p.recent_searches.map(x=>`<button class="recent-chip">${esc(x)}</button>`).join(''):'<span class="recent-chip">No searches yet 🎀</span>';[...r.querySelectorAll('button')].forEach(b=>b.onclick=()=>{$("#searchInput").value=b.textContent;state.searchMode='song';syncSearchMode();showView('home');doSearch(b.textContent)})}
  async function loadArtist(name){if(!name)return;state.artist=name;loading(true,`Opening ${name}…`);try{const d=await api(`/api/artist?name=${encodeURIComponent(name)}`);state.artist=d.artist;state.artistFollowed=!!d.followed;$("#artistName").textContent=d.artist;$("#artistHeroName").textContent=d.artist;$("#artistCount").textContent=`${d.tracks.length} Music Bunny picks`;syncFollowButton();renderArtistTracks(d.tracks);showView('artist')}catch(e){toast(e.message)}finally{loading(false)}}
  function syncFollowButton(){const b=$("#artistFollowBtn");b.textContent=state.artistFollowed?'✓ Following':'＋ Follow';b.classList.toggle('active',state.artistFollowed)}
  async function toggleArtistFollow(){if(!state.artist)return;try{const d=await api('/api/follow/toggle',{method:'POST',body:JSON.stringify({artist:state.artist})});state.artistFollowed=!!d.followed;syncFollowButton();toast(d.followed?`Following ${state.artist} 🌸`:`Unfollowed ${state.artist}`)}catch(e){toast(e.message)}}
  async function loadFollowing(){loading(true,'Opening followed artists…');try{const d=await api('/api/follows');const box=$("#followingCards");box.innerHTML='';$("#followingEmpty").classList.toggle('hidden',d.artists.length>0);d.artists.forEach(a=>{const btn=document.createElement('button');btn.className='following-card';btn.innerHTML=`<i>🌸</i><div><strong>${esc(a.name)}</strong><span>Open artist page</span></div><b>›</b>`;btn.onclick=()=>loadArtist(a.name);box.appendChild(btn)});showView('following')}catch(e){toast(e.message)}finally{loading(false)}}
  async function loadRelated(track){if(!track)return;loading(true,'Finding more like this…');try{const d=await api('/api/related',{method:'POST',body:JSON.stringify({source:track.source,source_id:track.source_id,index:track.index})});state.listMode='related';showView('list');renderTracks(d.tracks,`More from ${d.artist}`,'RELATED',`Based on “${d.based_on}”`)}catch(e){toast(e.message)}finally{loading(false)}}
  async function loadPlaylists(){loading(true,'Opening your playlists…');try{const d=await api('/api/playlists');state.playlists=d.playlists||[];renderPlaylists();showView('playlists')}catch(e){toast(e.message)}finally{loading(false)}}
  function renderPlaylists(){const b=$("#playlistCards");b.innerHTML='';$("#playlistEmpty").classList.toggle('hidden',state.playlists.length>0);state.playlists.forEach(p=>{const c=document.createElement('article');c.className='playlist-card';c.innerHTML=`<button class="playlist-open"><i>🎀</i><div><strong>${esc(p.name)}</strong><span>${p.count} songs</span></div><b>›</b></button><button class="playlist-delete">×</button>`;c.querySelector('.playlist-open').onclick=()=>openPlaylist(p.id);c.querySelector('.playlist-delete').onclick=async()=>{if(!confirm(`Delete “${p.name}”?`))return;await api(`/api/playlists/${p.id}`,{method:'DELETE'});loadPlaylists()};b.appendChild(c)})}
  async function createPlaylist(name){name=name.trim();if(!name){toast('Type a playlist name 🎀');return null}try{const d=await api('/api/playlists',{method:'POST',body:JSON.stringify({name})});toast(`Created “${d.playlist.name}” 🎀`);return d.playlist}catch(e){toast(e.message);return null}}
  async function openPlaylist(id){loading(true,'Opening playlist…');try{const d=await api(`/api/playlists/${id}`);state.activePlaylist=d.playlist;state.listMode='playlist';showView('list');renderTracks(d.tracks,d.playlist.name,'YOUR PLAYLIST',`${d.playlist.count} songs`)}catch(e){toast(e.message)}finally{loading(false)}}
  async function openPlaylistSheet(){if(!state.current)return;const d=await api('/api/playlists');state.playlists=d.playlists||[];const b=$("#playlistSheetList");b.innerHTML=state.playlists.length?state.playlists.map(p=>`<button class="sheet-playlist" type="button" data-id="${p.id}"><span>🎀</span><div><strong>${esc(p.name)}</strong><small>${p.count} songs</small></div><b>＋</b></button>`).join(''):'<p class="sheet-empty">Create your first playlist below.</p>';[...b.querySelectorAll('.sheet-playlist')].forEach(x=>x.onclick=()=>toggleCurrentInPlaylist(Number(x.dataset.id)));$("#playlistSheet").classList.remove('hidden')}
  function closePlaylistSheet(){$("#playlistSheet").classList.add('hidden')}
  async function toggleCurrentInPlaylist(id){if(!state.current)return;const d=await api(`/api/playlists/${id}/toggle`,{method:'POST',body:JSON.stringify({source:state.current.source,source_id:state.current.source_id,index:state.current.index})});toast(d.added?'Added to playlist 🎀':'Removed from playlist');closePlaylistSheet()}
  async function toggleFavorite(track,btn=null){try{const d=await api('/api/favorite/toggle',{method:'POST',body:JSON.stringify({source:track.source,source_id:track.source_id,index:track.index})});track.favorite=d.favorite;if(btn){btn.classList.toggle('loved',d.favorite);btn.textContent=d.favorite?'♥':'♡'}if(state.current?.id===track.id){$("#playerFav").textContent=d.favorite?'♥':'♡';$("#playerFav").classList.toggle('loved',d.favorite)}toast(d.favorite?'Saved to Favorites 🩷':'Removed from Favorites 🤍')}catch(e){toast(e.message)}}
  function fmt(sec){if(!Number.isFinite(sec)||sec<0)return'0:00';sec=Math.floor(sec);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
  function playTrack(track){state.current=track;state.currentIndex=Math.max(0,state.tracks.findIndex(t=>t.id===track.id));audio.src=track.stream_url;audio.play().catch(()=>toast('Tap play once more 🎧'));api('/api/play',{method:'POST',body:JSON.stringify({source:track.source,source_id:track.source_id,index:track.index})}).catch(()=>{});$("#playerTitle").textContent=track.title||track.name;$("#playerArtist").textContent=track.performer||'Music Bunny';$("#playerFav").textContent=track.favorite?'♥':'♡';$("#playerFav").classList.toggle('loved',track.favorite);$("#player").classList.remove('hidden');$("#playerToggle").textContent='❚❚';try{navigator.mediaSession.metadata=new MediaMetadata({title:track.title||track.name,artist:track.performer||'Music Bunny'})}catch(_){}}
  function nextIndex(direction=1){const n=state.tracks.length;if(!n)return-1;if(state.shuffle&&n>1){let x;do{x=Math.floor(Math.random()*n)}while(x===state.currentIndex);return x}let x=state.currentIndex+direction;if(x>=n)return state.repeat==='all'?0:-1;if(x<0)return state.repeat==='all'?n-1:0;return x}
  function playNext(manual=false){const i=nextIndex(1);if(i<0){if(manual&&state.tracks.length)playTrack(state.tracks[0]);else{$("#playerToggle").textContent='▶';audio.pause()}return}playTrack(state.tracks[i])}
  function playPrev(){if(audio.currentTime>5){audio.currentTime=0;return}const i=nextIndex(-1);if(i>=0)playTrack(state.tracks[i])}
  function syncRepeat(){const b=$("#playerRepeat");b.classList.toggle('active',state.repeat!=='off');b.textContent=state.repeat==='one'?'↻¹':'↻'}
  function shareCurrent(){if(!state.current)return;const text=`🎧 ${state.current.performer} — ${state.current.title}\nSearch it on @${BOT}`;const url=`https://t.me/share/url?url=${encodeURIComponent(`https://t.me/${BOT}`)}&text=${encodeURIComponent(text)}`;tg?.openTelegramLink?tg.openTelegramLink(url):window.open(url,'_blank')}
  function downloadTrack(track){const url=new URL(track.download_url,location.origin).href;const name=`${track.performer||'Music Bunny'} - ${track.title||'Song'}.mp3`.replace(/[\\/:*?"<>|]/g,'-').slice(0,90);try{if(tg?.downloadFile){tg.downloadFile({url,file_name:name},ok=>{if(!ok)location.href=url});return}}catch(_){}location.href=url}
  async function loadAdmin(){if(!state.isAdmin)return;loading(true,'Reading Music Bunny’s heartbeat…');try{const d=await api('/api/admin');renderAdmin(d);showView('admin')}catch(e){toast(e.message)}finally{loading(false)}}
  function renderAdmin(d){const s=d.stats;$("#adminStats").innerHTML=[["⚡",`${Math.round(s.avg_search_ms)} ms`,"Avg search"],["🎧",s.searches_today,"Searches today"],["✅",`${s.success_rate}%`,"Success"],["👥",s.users,"Users"],["💾",s.telegram_file_cache,"Telegram cache"],["🧠",s.aliases,"Learned aliases"],["🚀",`${d.runtime?.cache_hit_rate||0}%`,"Cache hit"],["📨",`${d.runtime?.telegram_file_hit_rate||0}%`,"File-ID hit"],["⏳",d.queue?.waiting||0,"Queue now"]].map(x=>`<div><i>${x[0]}</i><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('');const disc=d.discovery||{},extra=[{source:'spotify',status:disc.spotify?.configured?(disc.spotify.cooldown_seconds>0?'cooldown':'healthy'):'not configured',latency_ms:null,cooldown_seconds:disc.spotify?.cooldown_seconds||0},{source:'youtube',status:disc.youtube?.configured?(disc.youtube.cooldown_seconds>0?'cooldown':'healthy'):'not configured',latency_ms:null,cooldown_seconds:disc.youtube?.cooldown_seconds||0}];$("#sourceHealth").innerHTML=[...(d.sources||[]),...extra].map(x=>{const dot=x.status==='healthy'?'🟢':x.status==='cooldown'?'🟡':x.status==='unknown'?'⚪':'🔴';const detail=x.latency_ms?`${x.latency_ms} ms`:x.cooldown_seconds>0?`${Math.ceil(x.cooldown_seconds)}s cooldown`:x.status;return `<div class="source-row"><span>${dot} ${esc(x.source)}</span><small>${esc(detail)}</small></div>`}).join('');$("#adminTopSearches").innerHTML=(d.top_searches||[]).map(x=>`<div><strong>${esc(x.query)}</strong><span>${x.count}</span></div>`).join('')||'<p class="muted">No searches yet.</p>';$("#adminFailures").innerHTML=(d.recent_failures||[]).map(x=>`<div><strong>${esc(x.query||'—')}</strong><span>${Math.round(x.latency_ms)} ms · ${esc(x.surface)}</span></div>`).join('')||'<p class="muted">No recent failures 🎀</p>'}
  function syncSearchMode(){$$('.search-mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.searchMode));const input=$("#searchInput");input.placeholder=state.searchMode==='lyrics'?'Type a line you remember from the song…':state.searchMode==='artist'?'Type an artist name…':'Song, artist, or part of the title…';hideSuggestions()}
  $("#searchForm").addEventListener('submit',e=>{e.preventDefault();const q=$("#searchInput").value.trim();if(!q){toast('Type something first 🎧');return}doSearch(q)});$("#searchInput").addEventListener('input',e=>{clearTimeout(state.suggestTimer);state.suggestTimer=setTimeout(()=>loadSuggestions(e.target.value),180)});$("#searchInput").addEventListener('focus',e=>{if(e.target.value.trim().length>=2)loadSuggestions(e.target.value)});$$('.search-mode').forEach(b=>b.onclick=()=>{state.searchMode=b.dataset.mode;syncSearchMode()});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))hideSuggestions()});
  $$('[data-nav]').forEach(b=>b.onclick=()=>({favorites:loadFavorites,top:()=>loadTop(),profile:loadProfile,recent:loadRecent,playlists:loadPlaylists,recommendations:loadRecommendations,following:loadFollowing}[b.dataset.nav]?.()));$$('[data-tab]').forEach(b=>b.onclick=()=>{const t=b.dataset.tab;if(t==='home')showView('home');if(t==='favorites')loadFavorites();if(t==='profile')loadProfile()});$$('[data-back]').forEach(b=>b.onclick=()=>showView('home'));$$('#trendFilters button').forEach(b=>b.onclick=()=>loadTop(b.dataset.period));
  $("#refreshList").onclick=()=>state.listMode==='favorites'?loadFavorites():state.listMode==='top'?loadTop():state.listMode==='recent'?loadRecent():state.listMode==='recommendations'?loadRecommendations():state.listMode==='playlist'&&state.activePlaylist?openPlaylist(state.activePlaylist.id):state.listMode==='related'&&state.current?loadRelated(state.current):toast('Search again from Home 🎀');$("#refreshProfile").onclick=loadProfile;$("#artistRefresh").onclick=()=>state.artist&&loadArtist(state.artist);$("#artistFollowBtn").onclick=toggleArtistFollow;$("#followingRefresh").onclick=loadFollowing;$("#adminRefresh").onclick=loadAdmin;$("#adminBtn").onclick=loadAdmin;$("#playlistRefresh").onclick=loadPlaylists;$("#playlistCreateForm").addEventListener('submit',async e=>{e.preventDefault();const p=await createPlaylist($("#playlistNameInput").value);if(p){$("#playlistNameInput").value='';loadPlaylists()}});$("#playerPlaylist").onclick=openPlaylistSheet;$("#playlistSheetClose").onclick=closePlaylistSheet;$("#playlistSheetBackdrop").onclick=closePlaylistSheet;$("#playlistSheetCreate").addEventListener('submit',async e=>{e.preventDefault();const p=await createPlaylist($("#playlistSheetName").value);if(p){$("#playlistSheetName").value='';toggleCurrentInPlaylist(p.id)}});$("#groupBtn").onclick=()=>{const url=`https://t.me/${BOT}?startgroup=true`;tg?.openTelegramLink?tg.openTelegramLink(url):location.href=url};$("#ownerBtn").onclick=()=>location.href=`tg://openmessage?user_id=${OWNER_ID}`;
  $("#playerToggle").onclick=()=>{if(audio.paused){audio.play();$("#playerToggle").textContent='❚❚'}else{audio.pause();$("#playerToggle").textContent='▶'}};$("#playerFav").onclick=()=>state.current&&toggleFavorite(state.current);$("#playerPlaylist").onclick=openPlaylistSheet;$("#playerShare").onclick=shareCurrent;$("#playerRelated").onclick=()=>state.current&&loadRelated(state.current);$("#playerArtist").onclick=()=>state.current&&loadArtist(state.current.performer);$("#playerNext").onclick=()=>playNext(true);$("#playerPrev").onclick=playPrev;$("#playerShuffle").onclick=()=>{state.shuffle=!state.shuffle;$("#playerShuffle").classList.toggle('active',state.shuffle);toast(state.shuffle?'Shuffle on':'Shuffle off')};$("#playerRepeat").onclick=()=>{state.repeat=state.repeat==='off'?'all':state.repeat==='all'?'one':'off';syncRepeat();toast(state.repeat==='one'?'Repeat one':state.repeat==='all'?'Repeat all':'Repeat off')};$("#playerSeek").addEventListener('input',e=>{if(Number.isFinite(audio.duration)&&audio.duration>0)audio.currentTime=(Number(e.target.value)/1000)*audio.duration});
  audio.addEventListener('timeupdate',()=>{$("#playerCurrent").textContent=fmt(audio.currentTime);$("#playerDuration").textContent=fmt(audio.duration);if(Number.isFinite(audio.duration)&&audio.duration>0)$("#playerSeek").value=String(Math.round(audio.currentTime/audio.duration*1000))});audio.addEventListener('loadedmetadata',()=>$("#playerDuration").textContent=fmt(audio.duration));audio.addEventListener('play',()=>$("#playerToggle").textContent='❚❚');audio.addEventListener('pause',()=>$("#playerToggle").textContent='▶');audio.addEventListener('ended',()=>{if(state.repeat==='one'){audio.currentTime=0;audio.play()}else playNext(false)});try{navigator.mediaSession?.setActionHandler('play',()=>audio.play());navigator.mediaSession?.setActionHandler('pause',()=>audio.pause());navigator.mediaSession?.setActionHandler('nexttrack',()=>playNext(true));navigator.mediaSession?.setActionHandler('previoustrack',playPrev)}catch(_){}try{tg?.BackButton?.onClick(()=>showView('home'))}catch(_){}
  async function boot(){if(!tg?.initData){fatal('Open this page from the Music Bunny bot so Telegram can securely sign you in.');return}try{tg.ready();tg.expand();tg.setHeaderColor('#0d0914');tg.setBackgroundColor('#0a0710');if(tg.setBottomBarColor)tg.setBottomBarColor('#0a0710')}catch(_){}loading(true,'Waking up Music Bunny…');try{const d=await api('/api/bootstrap');$("#firstName").textContent=d.user.first_name||'cutie';state.profile=d.profile;state.isAdmin=!!d.user.is_admin;renderProfile(d.profile);$("#adminBtn").classList.toggle('hidden',!state.isAdmin);syncSearchMode();syncRepeat()}catch(e){console.error(e)}finally{loading(false)}}boot();
})();
